table fact_sales_budget
	lineageTag: b8d1f51a-9ed4-4515-af8f-e00e2ea9e86c

	measure TotalBudget = SUM(fact_sales_budget[Budget])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b6a487cc-379b-4368-b4c3-327eb8856b0a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure SalesOverBudget = ```
			
			    DIVIDE(
			        [TotalSales], 
			        [TotalBudget],
			        BLANK()    // Returns BLANK if division by zero
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7083bfdb-0905-4b14-bf2b-dcacbda273b7

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 053a0c34-00ab-4c72-bee4-ba04d914052f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 1f431e6d-1956-4b78-8187-d6994c950674
			defaultHierarchy: LocalDateTable_1320da11-b7d3-48e1-a85c-28f330cde4fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Budget
		dataType: int64
		formatString: 0
		lineageTag: c9833990-592d-4131-94e9-8963af8a9e71
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

	partition fact_sales_budget = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\pc\OneDrive\Work\Personal-Portfolio\internet-sales-analytics\datasets\SalesBudget.xlsx"), null, true),
				    Budget_Sheet = Source{[Item="Budget",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Budget_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Budget", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

